# Write your workflow for CI here
name: CodeCoverage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  automatism:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Setup coverage tool
        run: curl -Os https://uploader.codecov.io/latest/linux/codecov

      - name: Grant permissions
        run: chmod +x codecov

      - name: Run code coverage
        run: ./codecov -t <your-codecov-token-goes-here>